@apiUrl =  http://localhost:8080

###Get all rooms

GET {{apiUrl}}

###Get one product



GET {{apiUrl}}/bookings

### Create new product
POST {{apiUrl}}/bookings
Content-Type: application/json

{
  "room_id" : 1,
  "guest_id" : 1,
  "datefrom": "2026-05-01",
  "dateto" :"2026-05-10"
}


### Update Product info
##Uppdatera hela dataobjekt
PUT {{apiUrl}}/rooms
Content-Type: application/json

{
  "room_number" :404,
  "price" : 350
}


### Update Product info
##Patch kan uppdatera enskilda fält
PATCH {{apiUrl}}/1001
Content-Type: application/json

{
  "name" : "Jeans",
  "price" : 29
}




###Delete product
DELETE {{apiUrl}}/1004