apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-csi
  volumeMode: Filesystem
